#!/bin/sh
#
# find-getenv utility
# Copyright (c) 2012 Steve Grubb. ALL RIGHTS RESERVED.
# sgrubb@redhat.com
#
# This software may be freely redistributed under the terms of the GNU
# public license.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
# This program looks for setuid setgid apps that use getenv(2)
#
# To save to file: ./find-getenv | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g" | tee findings.txt

if [ -h /bin ] ; then
	libdirs="/usr/lib /usr/lib64"
	progdirs="/usr/bin /usr/sbin /usr/libexec"
else
	libdirs="/lib /lib64 /usr/lib /usr/lib64"
	progdirs="/bin /sbin /usr/bin /usr/sbin /usr/libexec"
fi
FOUND=0

# First param is which list to use, second is search pattern
scan () {
if [ "$1" = "1" ] ; then
	dirs=$libdirs
elif [ "$1" = "2" ] ; then
	dirs=$progdirs
elif [ "$1" = "3" ] ; then
	dirs=$3
fi

for d in $dirs ; do
	if [ ! -d $d ] ; then
		continue
	fi
	files=`/usr/bin/find $d -name "$2" -type f 2>/dev/null`
	for f in $files
	do
		syms=`/usr/bin/readelf -sW $f 2>/dev/null | egrep ' getenv@.*GLIBC'`
		if [ x"$syms" != "x" ] ; then
			# Only complain about setuid or setgid things
			syms=`find $f \( -perm -004000 -o -perm -002000 \) -type f -print`
			if [ x"$syms" != "x" ] ; then
				printf "\033[31m%-44s\033[m" $f
				rpm -qf --queryformat "\t%{SOURCERPM}" $f
				echo
				FOUND=1
#			else
#				printf "\033[33m%-44s\033[m" $f
			fi
		#rpm -qf --queryformat "%{NAME}-%{VERSION}" $f
		fi
	done
done
}

if [ $# -eq 1 ] ; then
	if [ -d $1 ] ; then
		scan 3 '*' $1
	else
		echo "Input is not a directory"
		exit 1
	fi
else
	scan 1 '*.so'
	scan 2 '*'
fi

if [ $FOUND -eq 0 ] ; then
        # Nothing to report, just exit
        echo "No problems found" 1>&2
        exit 0
fi
exit 1

