#!/bin/sh
# This checks for unconfined apps running, initrc and inetd are signs
# of missing transitions.

pidof xinetd >/dev/null
if [ $? -eq 0 ] ; then
ps -eZ | grep -E "initrc|inetd" | grep -Ev `pidof xinetd` | tr ':' ' ' | awk '{ printf "%s %s\n", $3, $NF }'
else
ps -eZ | grep "initrc" | tr ':' ' ' | awk '{ printf "%s %s\n", $3, $NF }'
fi
