#!/bin/sh

# Critical sysctls:
# =================
# protected_hardlinks = 0 no, *1 yes
# protected_symlinks = 0 no, *1 yes
# suid_dumpable = *0 no, 1 yes
# dmesg_restrict = 0 everyone, *1 restricted
# perf_event_paranoid = *2 no events, 1 perf data, 0 everything
# randomize_va_space = *2 all, 1 mmap, 0 none
# ptrace_scope = 0 none, 1 trace child, *2 CAP_SYS_PTRACE, 3 none
# legacy_va_layout = 1 use legacy layout, *0 new layout

critical="protected_hardlinks|protected_symlinks|suid_dumpable|dmesg_restrict|perf_event_paranoid|randomize_va_space|legacy_va_layout|kernel.yama"
other="usermodehelper.bset|usermodehelper.inheritable|kernel.*shield|cad_pid|mmap_rnd_"

if [ $1 = "--critical" ] ; then
	/usr/sbin/sysctl -a 2>/dev/null | egrep "$critical"
else
	/usr/sbin/sysctl -a 2>/dev/null | egrep "$critical|$other"
fi
